# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/connection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/connection.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z\035github.com/gjagnoor/budget/pb',
  serialized_pb=b'\n\x13pb/connection.proto\x12\x02pb\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x18\n\x06Income\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"\x19\n\x07\x45xpense\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"]\n\x18summaryThisMonthResponse\x12\x14\n\x0ctotalIncomes\x18\x01 \x01(\x05\x12\x15\n\rtotalExpenses\x18\x02 \x01(\x05\x12\x14\n\x0ctotalSavings\x18\x03 \x01(\x05\"U\n\x17summaryThisMonthRequest\x12\x1b\n\x07incomes\x18\x01 \x03(\x0b\x32\n.pb.Income\x12\x1d\n\x08\x65xpenses\x18\x02 \x03(\x0b\x32\x0b.pb.Expense2n\n\x07Greeter\x12.\n\x08SayHello\x12\x10.pb.HelloRequest\x1a\x0e.pb.HelloReply\"\x00\x12\x33\n\rSayHelloAgain\x12\x10.pb.HelloRequest\x1a\x0e.pb.HelloReply\"\x00\x32]\n\x07Summary\x12R\n\x13GetSummaryThisMonth\x12\x1b.pb.summaryThisMonthRequest\x1a\x1c.pb.summaryThisMonthResponse\"\x00\x42\x1fZ\x1dgithub.com/gjagnoor/budget/pbb\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='pb.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pb.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='pb.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pb.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=86,
)


_INCOME = _descriptor.Descriptor(
  name='Income',
  full_name='pb.Income',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='pb.Income.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=112,
)


_EXPENSE = _descriptor.Descriptor(
  name='Expense',
  full_name='pb.Expense',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='pb.Expense.amount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=139,
)


_SUMMARYTHISMONTHRESPONSE = _descriptor.Descriptor(
  name='summaryThisMonthResponse',
  full_name='pb.summaryThisMonthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='totalIncomes', full_name='pb.summaryThisMonthResponse.totalIncomes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalExpenses', full_name='pb.summaryThisMonthResponse.totalExpenses', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalSavings', full_name='pb.summaryThisMonthResponse.totalSavings', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=234,
)


_SUMMARYTHISMONTHREQUEST = _descriptor.Descriptor(
  name='summaryThisMonthRequest',
  full_name='pb.summaryThisMonthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='incomes', full_name='pb.summaryThisMonthRequest.incomes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expenses', full_name='pb.summaryThisMonthRequest.expenses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=321,
)

_SUMMARYTHISMONTHREQUEST.fields_by_name['incomes'].message_type = _INCOME
_SUMMARYTHISMONTHREQUEST.fields_by_name['expenses'].message_type = _EXPENSE
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Income'] = _INCOME
DESCRIPTOR.message_types_by_name['Expense'] = _EXPENSE
DESCRIPTOR.message_types_by_name['summaryThisMonthResponse'] = _SUMMARYTHISMONTHRESPONSE
DESCRIPTOR.message_types_by_name['summaryThisMonthRequest'] = _SUMMARYTHISMONTHREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'pb.connection_pb2'
  # @@protoc_insertion_point(class_scope:pb.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'pb.connection_pb2'
  # @@protoc_insertion_point(class_scope:pb.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

Income = _reflection.GeneratedProtocolMessageType('Income', (_message.Message,), {
  'DESCRIPTOR' : _INCOME,
  '__module__' : 'pb.connection_pb2'
  # @@protoc_insertion_point(class_scope:pb.Income)
  })
_sym_db.RegisterMessage(Income)

Expense = _reflection.GeneratedProtocolMessageType('Expense', (_message.Message,), {
  'DESCRIPTOR' : _EXPENSE,
  '__module__' : 'pb.connection_pb2'
  # @@protoc_insertion_point(class_scope:pb.Expense)
  })
_sym_db.RegisterMessage(Expense)

summaryThisMonthResponse = _reflection.GeneratedProtocolMessageType('summaryThisMonthResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYTHISMONTHRESPONSE,
  '__module__' : 'pb.connection_pb2'
  # @@protoc_insertion_point(class_scope:pb.summaryThisMonthResponse)
  })
_sym_db.RegisterMessage(summaryThisMonthResponse)

summaryThisMonthRequest = _reflection.GeneratedProtocolMessageType('summaryThisMonthRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYTHISMONTHREQUEST,
  '__module__' : 'pb.connection_pb2'
  # @@protoc_insertion_point(class_scope:pb.summaryThisMonthRequest)
  })
_sym_db.RegisterMessage(summaryThisMonthRequest)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='pb.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=323,
  serialized_end=433,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='pb.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayHelloAgain',
    full_name='pb.Greeter.SayHelloAgain',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER


_SUMMARY = _descriptor.ServiceDescriptor(
  name='Summary',
  full_name='pb.Summary',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=435,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSummaryThisMonth',
    full_name='pb.Summary.GetSummaryThisMonth',
    index=0,
    containing_service=None,
    input_type=_SUMMARYTHISMONTHREQUEST,
    output_type=_SUMMARYTHISMONTHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUMMARY)

DESCRIPTOR.services_by_name['Summary'] = _SUMMARY

# @@protoc_insertion_point(module_scope)
